### ISSUE TITLE
config: Directory ConfigLoader

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#255]
It will look in the directory and start building a `dict`, each folder becomes a key in the dict.

Go good way to test this is to export the `service/http/tests/dataflow.py` `HELLO_BLANK_DATAFLOW` and then split out the subflow for `remap_to_response`:

### Old Version

**hello_blank.yaml**

```yaml
configs:
  hello_blank:
    formatting: Hello {}
  remap_to_response:
    dataflow:
      configs: {}
      flow:
        get_formatted_message:
          inputs:
            spec:
            - seed
      operations:
        get_formatted_message:
          inputs:
            spec:
              name: get_single_spec
              primitive: array
          name: get_single
          outputs:
            output:
              name: get_single_output
              primitive: map
          stage: output
      seed:
      - definition:
          name: get_single_spec
          primitive: array
        value:
        - message
definitions:
  format_data:
    name: format_data
    primitive: string
  message:
    name: message
    primitive: string
  remap_output:
    name: remap_output
    primitive: map
  remap_spec:
    name: remap_spec
    primitive: map
flow:
  hello_blank:
    inputs:
      data:
      - seed
  remap_to_response:
    inputs:
      spec:
      - seed
linked: true
operations:
  hello_blank:
    inputs:
      data: format_data
    name: formatter
    outputs:
      string: message
    stage: processing
  remap_to_response:
    inputs:
      spec: remap_spec
    name: remap
    outputs:
      response: remap_output
    stage: output
seed:
- definition: remap_spec
  value:
    response:
    - message
```

### New Version

**hello_blank.yaml**

```yaml
configs:
  hello_blank:
    formatting: Hello {}
definitions:
  format_data:
    name: format_data
    primitive: string
  message:
    name: message
    primitive: string
  remap_output:
    name: remap_output
    primitive: map
  remap_spec:
    name: remap_spec
    primitive: map
flow:
  hello_blank:
    inputs:
      data:
      - seed
  remap_to_response:
    inputs:
      spec:
      - seed
linked: true
operations:
  hello_blank:
    inputs:
      data: format_data
    name: formatter
    outputs:
      string: message
    stage: processing
  remap_to_response:
    inputs:
      spec: remap_spec
    name: remap
    outputs:
      response: remap_output
    stage: output
seed:
- definition: remap_spec
  value:
    response:
    - message
```

**configs/remap_to_response/dataflow.yaml**

```yaml
configs: {}
flow:
  get_formatted_message:
    inputs:
      spec:
      - seed
operations:
  get_formatted_message:
    inputs:
      spec:
        name: get_single_spec
        primitive: array
    name: get_single
    outputs:
      output:
        name: get_single_output
        primitive: map
    stage: output
seed:
- definition:
    name: get_single_spec
    primitive: array
  value:
  - message
```
