### ISSUE TITLE
config: Add ability to specify command line flags via a config file

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#409]
```console
$ dffml train \
  -model scikitlr \
  -model-features Years:int:1 Expertise:int:1 Trust:float:1 \
  -model-predict Salary:float:1 \
  -sources f=csv \
  -source-filename training.csv
```

Would be equivalent to

```console
$ dffml train @tf_model.yml @database_sources.yml
```

*model.yml*

```yaml
model:
  arg: scikitlr
  config:
    features:
    - name: Years
      dtype: int
      length: 1
    - name: Expertise:int
      dtype: int
      length: 1
    - name: Trust
      dtype: float
      length: 1
    predict:
      dtype: int
      length: 1
      name: maintained
```

*sources.yml*

**TODO Figure out how to do sources in yaml file, tricky because of need to configure Sources class, and deal with tagged entrypoints**

Related: #326, https://intel.github.io/dffml/master/contributing/codebase.html#config
