### ISSUE TITLE
df: types: DataFlow: Implement syntax for flow where we can specify multiple definitions an Input can be

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#607]
```
flow:
  edit_feature:
    inputs:
      feature:
      - seed:
        - Years
        - Trust
        - Expertise
        - Salary
```

Related: #604

Places that will need updating:

- https://github.com/intel/dffml/blob/master/dffml/df/types.py#L517
- Somewhere in https://github.com/intel/dffml/blob/master/dffml/df/memory.py dealing with dataflow.by_origin
