### ISSUE TITLE
dataflow: operation : Support shared config

### ISSUE THREAD

**Issue by aghinsa** [intel/dffml#720]
Now we don't have a way for operations in dataflow to share objects.so if we have a dataflow,

```

configs:
  db_lookup:
    database:
      config:
        filename: test.db
      plugin: sqlite
  db_query:
    database:
      config:
        filename: test.db
      plugin: sqlite
```
two connections are made into the database as config is initialized two times.

A possible solution is to support something like
```
sdb = SqliteDatabase(SqliteDatabaseConfig(filename="test.db"))

dataflow = DataFlow(
    operations={
        "db_query": db_query_create_table.op,
        "db_lookup": db_query_lookup.op,
        "get_single": GetSingle.imp.op,
    },
    configs={"db_query": "db", "db_lookup": "db",},
    sharedconfigs={"db": DatabaseQueryConfig(database=sdb)},
```
